# Peloton Prodview: Routes
# Field route management for data collection and operator assignments
#
# Types: dt=datetime bool=boolean int=integer dbl=double
#   s{N}=string(N) txt{N}=stringlong(N) s32_calc=calculated_string32
#   dbl_m3=m3 dbl_m3_calc=m3(calc) dbl_kPa=kPa dbl_degC=degC
#   dbl_pct=proportion dbl_m3pm3=m3/m3 dbl_kgpm3=kg/m3 dbl_m3pd=m3/day
#   dbl_deg=degrees dbl_kg=kilograms dbl_days=days dbl_day=day dbl_sec=seconds
#   dbl_calc=double(calc) dt_calc=datetime(calc)
#
# OMITTED (on all tables): IDFlowNet sysLock* sysMod* sysCreate*
#   sysTag sysSecurityTyp IDRec IDRecParent *TK columns


# Tables in this domain (column details in tables/ directory):
#   pvUnitUserIDCalc: Unit Route Security User IDs +parent | List of User ID's that have edit right...
#   pvUnitDateListCalc: List of Visible Entry Dates +parent | List of dates that are visible with cur...
#   pvRouteSet: Route Set | In the Route Set table, enter the date in which a series of route...
#   pvRouteSetRoute: Routes +parent | Routes are the series of stops on which measurements are mad...
#   pvRouteSetRouteUnit: Route Units +parent | Route units are the locations that an operator travels ...
#   pvRouteSetRouteVwFlowDiag: Other Units Displayed on Diagram +parent | Components of the network to displ...
#   pvRouteSetRouteDtListCalc: List of Visible Entry Dates +parent | List of dates that are visible with cur...
#   pvRouteSetRouteUserID: Route Name User IDs +parent | List of User ID's that have security rights to ...
